name: graalvm-native-image-toolchain
description: Configures a complete toolchain for building GraalVM Native Image applications
author: helpermethod
branding:
  icon: box  
  color: blue
inputs:
  graalvm-version:
    description: The GraalVM version
    required: true
  java-version:
    description: The Java version
    required: true

runs:
  using: composite
  steps:
    - name: Set up GraalVM
      uses: ayltai/setup-graalvm@v1
      with:
        graalvm-version: ${{ inputs.graalvm-version }}
        java-version: ${{ inputs.java-version }}
        native-image: true
    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
