name: graalvm-native-image-toolchain
description: Sets up a complete toolchain for building GraalVM Native Image applications
inputs:
  graalvm-version:
    required: true

runs:
  using: composite
  steps:
    - name: Set up GraalVM
      uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm-version: {{inputs.graalvm-version}}
    - name: Install Native Image
      run: ${{ runner.os == 'Windows' && 'gu.cmd' || 'gu'}} install native-image
    - name: Setup Developer Command Prompt
      if: ${{ runner.os == 'Windows' }}
      uses: ilammy/msvc-dev-cmd@v1
