name: test
on: push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up GraalVM Native Image toolchain
        id: graalvm-native-image-toolchain
        uses: ./
        with:
          graalvm-version: 21.2.0
          java-version: 11
      - name: Print Java version
        run: java --version
      - name: Print GraalVM
        run: native-image --version
      - name: Print cl.exe version
        if: {{ runner.os == 'Windows' }}
        run: cl.exe
